name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub (optional, for pushing)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ var.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t assetservice:${{ github.sha }} .

    # Push the Docker image to Docker Hub (optional)
    - name: Push Docker image
      run: |
        docker tag assetservice:${{ github.sha }} rajshreemittalnagarro/assetservice:latest
        docker push assetservice:${{ github.sha }}
        docker push rajshreemittalnagarro/assetservice:latest

